docs_metadata_enhancer/apps/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [

    path('accounts/profile/', views.ProfileUpdateView.as_view(), name='profile'),
 
    path('accounts/profile/edit', views.ProfileUpdateView.as_view(), name='profile_edit'),
    path('accounts/signup/', views.SignupView.as_view(), name='signup'),
    path("accounts/login/", auth_views.LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("activate/<uidb64>/<token>", views.activate, name='activate'),
    path(
        'accounts/reset_password/',
        views.PasswordResetView.as_view(),
        name="reset_password"),
    path(
        'accounts/reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset/password_reset_sent.html"),
        name='password_reset_done'),
    path(
        'accounts/reset/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm"),
    path(
        'accounts/reset/done',
         auth_views.PasswordResetCompleteView.as_view(
         template_name="accounts/password_reset/password_reset_done.html"),
         name="password_reset_complete"),
]

docs_metadata_enhancer/docs_metadata_enhancer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls', namespace='accounts')),
    path('', include('apps.enhancer.urls', namespace='courses')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docs_metadata_enhancer/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from PIL import Image
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError("The Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None

    #inherited fields: username, email, first_name, last_name, password, is_staff, is_active 

    email = models.EmailField("Email address", unique=True)
    image = models.ImageField(
        "Image", default="default_account_picture.png", upload_to='account_pictures')
    phone_number = PhoneNumberField(blank=True) #https://django-phonenumber-field.readthedocs.io/
    approved =  models.BooleanField(default=False)
    is_manager =  models.BooleanField(default=False)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta:
        verbose_name = "Users"
        verbose_name_plural = "Users"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def __str__(self,):
        return f'{self.first_name} {self.last_name}, {self.email}, {self.phone_number}'

    def get_absolute_url(self):
        return reverse('accounts:profile')

docs_metadata_enhancer/apps/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


class UserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'password1', 'password2']


#https://django-phonenumber-field.readthedocs.io/
class ProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ['image', 'email', 'first_name', 'last_name' ,'phone_number']

docs_metadata_enhancer/apps/accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (PasswordResetConfirmView,
                                       PasswordResetView)
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import CreateView, ListView, UpdateView

from .forms import ProfileForm, UserCreationForm
from .models import User
from .tokens import account_activation_token
from .utils import send_account_email_confirmation

# Create your views here.


class SignupView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'accounts/signup.html'
    redirect_authenticated_user = False

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a register page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        valid = super().form_valid(form)
        user = form.save()
        user.is_active = False
        user.save()
        try:
            send_account_email_confirmation(self.request, user)
        except Exception as e:
            print(f"Error: {e}")
        return valid

    def get_success_url(self):
        return '/'


@login_required
def profile_details(request):
    user = request.user

    context = {
        "user": user,
    }
    return render(request, 'accounts/profile.html', context)

class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileForm
    template_name = "accounts/profile.html"

    def get_object(self):
        return get_object_or_404(User, id=self.request.user.id)
    
class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileForm
    template_name = "accounts/profile_edit.html"

    def get_object(self):
        return get_object_or_404(User, id=self.request.user.id)


class PasswordResetView(PasswordResetView):
    template_name = "accounts/password_reset/password_reset.html"
    email_template_name = 'accounts/email_messages/password_reset_email.txt'
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "accounts/password_reset/password_reset_form.html"
    success_url = reverse_lazy('accounts:password_reset_complete')


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Спасибо за подтверждение Email. Теперь вы можете войти.')
        return redirect('accounts:login')
    else:
        messages.error(request, 'Срок действия ссылки истёк')
        return redirect('accounts:login')

docs_metadata_enhancer/apps/accounts/templates/accounts/login.html
{%  extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col text-center">
      <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="mb-4 mt-5">
                <h3>Вход в аккаунт</h3>
                <p class="mb-4">Войдите для продолжения.</p>
            </div>
        <form class="p-4 p-md-5 border rounded-3 bg-light" method="POST" action="">
            {% csrf_token %}
            
          <div class="form-floating mb-3">
            <input type="email" name="username"class="form-control" id="username" placeholder="Username">
            <label for="username">E-mail</label>
          </div>

          <div class="form-floating mb-3">
            <input type="password" name="password" class="form-control" id="password" placeholder="Password">
            <label for="password">Пароль</label>
          </div>

          <button class="w-100 btn btn-lg btn-primary" type="submit" value="login">Войти</button>

            <div class="mt-2">
                <span class="ml-auto"><a href="{% url 'accounts:reset_password'%}" class="forgot-pass">Забыли пароль?</a></span> 
            </div>

          <hr class="my-4">
          <medium class="text-muted">Нету аккаунта? <a href="{% url 'accounts:signup' %}" class="ml-2">Зарегистрируйтесь</a></medium>
        </form>
        </div>
      </div>
      
    </div>
    
  </div>
{% endblock %}

docs_metadata_enhancer/apps/accounts/templates/accounts/profile.html
{%  extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section mt-3">
    <div class="container p-0" >
        <div class="row d-flex justify-content-start">
            <div class="col-md-3 d-flex flex-column p-0">
            </div>
            <div class="col-md-8" >
                <div class="d-flex flex-row justify-content-start flex-wrap" >
                  {%for course in user_courses%}
                  <div class="d-flex flex-column justify-content-start mt-3 ms-5" style="max-width: 230px;">
                    <img src="{{course.image.url}}" style="max-width: 230px;" height="130" class="rounded-3" alt="Course Cover Image">
                    <p class="fs-5 fw-bold mt-1 mb-0"><a href="" class="text-decoration-none">{{course.title}}</a></p>
                    <p class="fs-7 text-secondary mt-0">
                      {{course.author.first_name}} {{course.author.last_name}} 
                      <a href="" class="btn btn-sm btn-outline-dark border border-1 border-dark ms-2" >Архивировать</a>

                    </p>  
                  </div>
                  {%endfor%}
                </div>
                  </div>
            </div>
        </div>
    </div>
{% endblock %}

docs_metadata_enhancer/apps/accounts/templates/accounts/profile_edit.html
{%  extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <div class="media" style="display: flex; flex-direction: column; align-items: center;">
        <img class="rounded-circle account-img" src="{{ user.image.url }}" width="150" height="150">
        <div class="media-body">
            {% if user.first_name%}
            <h2 class="account-heading">Привет, <strong>{{ user.first_name }}</strong> </h2>
            {%else%}
            <h2 class="account-heading">Заполните ваши личные данные</h2>
            {%endif%}
        </div>  
    </div> 
    <div class="container" >
        <div class="row d-flex justify-content-center">
            <div class="col-md-6" >
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group align-content-center">
                        <legend class="border-bottom mb-4"></legend>
                        {{ form|crispy }}
                    </fieldset>
            </div>

                <div class="form-group" style="display: flex; flex-direction: column; align-items: center;">
                    <button class="w-50 btn btn-lg btn-primary mt-3" type="submit">Обновить</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

docs_metadata_enhancer/apps/accounts/templates/accounts/signup.html
{%  extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col text-center">
      <div class="row justify-content-center">
        <div class="col-md-3">
            <div class="mb-4 mt-5">
                <h3>Регистрация</h3>
                <p class="mb-4">Создайте учётную запись</p>
            </div>
            <form class="p-4 p-md-5 border rounded-3 bg-light" method="POST" action="">
                {% csrf_token %}

              <div class="form-floating mb-3">
                <input type="email" name="email" class="form-control" id="email" placeholder="Email">
                <label for="email">Email</label>
              </div>

              <div class="form-floating mb-3">
                <input type="password" name="password1" class="form-control" id="password1" placeholder="Password">
                <label for="password">Пароль</label>
              </div>

              <div class="form-floating mb-3">
                <input type="password" name="password2" class="form-control" id="password2" placeholder="Password">
                <label for="password">Подтверждение пароля</label>
              </div>

              <button class="w-100 btn btn-lg btn-dark" type="submit" value="login">Продолжить</button>

              <hr class="my-4">
              <medium class="text-muted">Уже есть аккаунт? <a href="{% url 'accounts:login' %}" class="ml-2">Войти</a></medium>
            </form>
        </div>
      </div>
      
    </div>
    
  </div>
{% endblock %}